### ISSUE TITLE
Github code not identical to the deployed code

### ISSUE THREAD

**Issue by thyrfa** [nccgroup/typofinder#62]
At https://labs.nccgroup.trust/typofinder/ when I run massmutual.com it includes amssmutual[.]com in the list, which is good, but then running the github code locally does not return that domain.  There are a total of 4 domains that are missed like that.  Then there is also the issue that getting a 502 just returns an error instead of retrying which means a lot more domains are missed.

**Comment by olliencc** [comment]
Hi,

Correct. 

We forked internally and integrated with some other data sources which allow other means of searching which is why labs returns more. 

The labs version is not considered a production service but rather an experiment hence sometimes it runs into scaling issues. Our commercialization of this concept/code is Domain Intelligence which is C# based.

Cheers

Ollie
